/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:e429052d-7b80-4a39-a72a-816dc7eb8fad",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_0TajEbltl",
    "aws_user_pools_web_client_id": "6jha7k3ehff69ic8h0hpvb7oj3",
    "oauth": {}
};


export default awsmobile;
