/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:e429052d-7b80-4a39-a72a-816dc7eb8fad",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_0TajEbltl",
    "aws_user_pools_web_client_id": "6jha7k3ehff69ic8h0hpvb7oj3",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3k5moy5eurcslfrsehvtnkmcpa.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-t4cm6gaj6nhtzio65z36y76tbe"
};


export default awsmobile;
